// Copyright 2015 <chaishushan{AT}gmail.com>. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Auto Generated By 'go generate', DONOT EDIT!!!

// +build cgo

#include "./internal/protobuf-cpp-3.0.0-alpha-2/src/google/protobuf/compiler/java/java_service.cc"
